name: Spellcheck
on:
  push:
    branches: [main]
    paths:
      - '**/*.yml'
    paths-ignore:
      - '.github/**/*.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.yml'
    paths-ignore:
      - '.github/**/*.yml'
  workflow_dispatch:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v6
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
      with:
        source_files: resume-en.yml
  # check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v6

  #     - name: Spellcheck
  #       uses: igsekor/pyspelling-any@v1
  #       # with:
  #       #   configFile: '.my-custom-config.yml'
